apply plugin: 'com.android.application'

android {
    compileSdk 34
    namespace 'com.eunaman.pcm'

    signingConfigs {
        release {
            storeFile file('../eunaman.keystore')
            storePassword 'eunaman2024'
            keyAlias 'eunaman'
            keyPassword 'eunaman2024'
        }
    }

    defaultConfig {
        applicationId "com.eunaman.pcm"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
            debuggable true
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    // Filtro para evitar conflitos de ABI
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.browser:browser:1.7.0'
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
